name: Deploy Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy-lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.1.0
              with:
                node-version: 22
            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-region: sa-east-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: Install dependencies
              env:
                CI: true
              run: npm ci
            - name: Deploy
              run: |
                # Construir
                npx ncc build index.ts 
                # Empaquetar
                zip -j deploy.zip ./dist/*
                # Subir
                aws lambda update-function-code --function-name=recibirSaludo --zip-file=fileb://deploy.zip
            
