name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
    deploy-lambda:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.1.0
              with:
                node-version: 22
            - name: Install dependencies
              env:
                CI: true
              run: npm ci
            
